export * from './product.interface';
export * from './user.interface';
export * from './auth.interface';
export * from './query-params.interface';
export * from './cliente.interface';
export * from './categoria.interface';
export * from './departamento.interface';
export * from './mesa.interface';
export * from './sala.interface';
